version: '3'

services:
  mpi_head:
    image: gianv9/docker-hpc:ubuntu-openmpi-latest
    ports: 
      - "22"

  mpi_node: 
    image: gianv9/docker-hpc:ubuntu-openmpi-latest
    deploy:
      replicas: 10
