version: '3.3'

services:
  master:
    image: gianv9/docker-hpc:ubuntu-openmpi-latest
    ports: 
      - "22"
    user: "root"
    entrypoint: ["mpi_bootstrap", "role=master", "mpi_master_service_name=master", "mpi_worker_service_name=worker"]

  worker: 
    image: gianv9/docker-hpc:ubuntu-openmpi-latest
    user: "root"
    entrypoint: ["mpi_bootstrap", "role=worker", "mpi_master_service_name=master", "mpi_worker_service_name=worker"]
    deploy:
      replicas: ${REPLICAS}
