version: '3.3'

services:
  master:
    image: ${IMAGE_NAME}
    user: root
    entrypoint: [
      "mpi_bootstrap", 
      "role=master", 
      "mpi_master_service_name=master", 
      "mpi_worker_service_name=worker"
      ]
    ports:
      - "${MASTER_PORT}:22"
    deploy:
      placement:
        constraints:
          - node.labels.script_bearer == true
      resources:
        limits:
          cpus: '1'
    volumes:
      - "${MASTER_SHARED_FOLDER}:/project/shared"

  worker:
    image: ${IMAGE_NAME}
    deploy:
      replicas: ${REPLICAS}
      resources:
        limits:
          cpus: '1'
    user: root
    entrypoint: ["mpi_bootstrap", "role=worker", "mpi_master_service_name=master", "mpi_worker_service_name=worker"]

    volumes:
      # when the swarm has more than one node, ${SHARED_FOLDER}=sshsf
      # so the vieux plugin volume is used
      - "${WORKER_SHARED_FOLDER}:/project/shared"

volumes:
  sshfs:
    driver: vieux/sshfs:latest
    driver_opts:
      sshcmd: "${SCRIPT_BEARER_USER}${SCRIPT_BEARER_IP}:${CURRENT_DIR}/${SHARED_FOLDER}"
      # password: "${PASSWORD}"
      allow_other: ""